
# POST http://localhost:3000/api/posts/:postId?sort=ASC
POST http://localhost:3000/api/posts/
Content-Type: application/json

{
  "title": "CSS is great",
  "author": "Jill",
  "body": "css is flex",
  "rating": 5
}

###
GET http://localhost:3000/api/posts 

###

GET http://localhost:3000/api/first-posts 
###

GET http://localhost:3000/api/posts/name/Mike
###

GET http://localhost:3000/api/posts-by-rating
###

GET http://localhost:3000/api/posts-by-rating?order=sdsds&limit=5

###

DELETE http://localhost:3000/api/posts/10

### 

POST http://localhost:3000/api/categories/create
Content-Type: application/json