
# POST http://localhost:3001/api/posts/:postId?sort=ASC
POST http://localhost:3001/api/posts/
Content-Type: application/json

{
  "title": "CSS is great",
  "author": "Mike",
  "body": "Use grid layout",
  "rating": 3
}

###
GET http://localhost:3001/api/posts 

###

GET http://localhost:3001/api/first-posts 
###

GET http://localhost:3001/api/posts/name/Mike
###

GET http://localhost:3001/api/posts-by-rating
###

GET http://localhost:3001/api/posts-by-rating?order=sdsds&limit=5

###

DELETE http://localhost:3001/api/posts/10